# Generated by Django 5.1.4 on 2026-03-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_make_address_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['floor', 'unit_number']},
        ),
    ]
