# Generated by Django 5.1.6 on 2026-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_propertycharge"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name="propertycharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="property_charge_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("rent_amount__gt", 0)), name="unit_rent_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__gte", 0)),
                name="unit_deposit_nonnegative",
            ),
        ),
    ]
