# Generated by Django 5.2.17 on 2026-08-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_unit_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lr_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
