# Generated by Django 5.2.17 on 2026-09-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_lr_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='properties.propertycharge')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='properties.unit')),
            ],
            options={
                'db_table': 'meter_readings',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('unit', 'charge', 'period'), name='meter_reading_once_per_period'), models.CheckConstraint(condition=models.Q(('reading__gte', 0)), name='meter_reading_nonnegative')],
            },
        ),
    ]
