# Generated by Django 5.1.4 on 2026-04-03 13:48

import apps.core.utils.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_occupation_next_of_kin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_back_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[apps.core.utils.phone.validate_phone]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='E.164 format (e.g. +254712345678)', max_length=15, unique=True, validators=[apps.core.utils.phone.validate_phone]),
        ),
    ]
