# Generated by Django 5.2.17 on 2026-08-25 16:57

import apps.core.utils.kra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_created_by_alter_user_id_document_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.utils.kra.validate_kra_pin]),
        ),
    ]
