# Generated by Django 5.1.4 on 2026-04-03 13:50

import apps.core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage_backends.PublicMediaStorage(), upload_to='maintenance/%Y/%m/'),
        ),
    ]
