# Generated by Django 5.1.6 on 2026-07-30 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0006_alter_unit_unique_together_alter_unit_unit_number_and_more",
        ),
        ("tenants", "0004_lease_document_key_private_maintenance_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="maintenance/%Y/%m/"
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("rent_amount__gt", 0)), name="lease_rent_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__gte", 0)),
                name="lease_deposit_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="lease_dates_valid",
            ),
        ),
    ]
