# Generated by Django 5.1.15 on 2026-07-31 13:24

import apps.core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_maintenancerequest_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage_backends.private_media_storage, upload_to='maintenance/%Y/%m/'),
        ),
    ]
