# Generated by Django 5.2.17 on 2026-08-25 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_unit_payment_code'),
        ('tenants', '0007_rename_lease_to_tenancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenancy',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='tenancy',
            name='lease_rent_positive',
        ),
        migrations.RemoveConstraint(
            model_name='tenancy',
            name='lease_deposit_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='tenancy',
            name='lease_dates_valid',
        ),
        migrations.RenameIndex(
            model_name='tenancy',
            new_name='tenancies_status_0a463c_idx',
            old_name='leases_status_08f63f_idx',
        ),
        migrations.RenameIndex(
            model_name='tenancy',
            new_name='tenancies_tenant__0afc40_idx',
            old_name='leases_tenant__efe78a_idx',
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.unit'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(('rent_amount__gt', 0)), name='tenancy_rent_positive'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='tenancy_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='tenancy_dates_valid'),
        ),
    ]
