# Generated by Django 5.2.17 on 2026-08-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='notice_effective_date',
            field=models.DateField(blank=True, help_text='The day the tenant intends to vacate.', null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='notice_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='notice_reason',
            field=models.TextField(blank=True, help_text="The tenant's own words, kept as the written record."),
        ),
    ]
