# Generated by Django 5.2.17 on 2026-09-28 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenancy_notice_effective_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='notice_given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='notice_effective_date',
            field=models.DateField(blank=True, help_text='The last day the tenant may occupy the unit.', null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='notice_reason',
            field=models.TextField(blank=True, help_text='The written reason for the notice, kept verbatim as the record.'),
        ),
    ]
