# Generated by Django 5.2.17 on 2026-09-28 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_notice_given_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_held', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_to_arrears', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant_owes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forfeited', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_method', models.CharField(blank=True, max_length=20)),
                ('refund_reference', models.CharField(blank=True, max_length=100)),
                ('settled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_settlement', to='tenants.tenancy')),
            ],
            options={
                'db_table': 'deposit_settlements',
            },
        ),
        migrations.CreateModel(
            name='SettlementDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='tenants.depositsettlement')),
            ],
            options={
                'db_table': 'deposit_settlement_deductions',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='depositsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_held__gte', 0)), name='settlement_held_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depositsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('refund_due__gte', 0)), name='settlement_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depositsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('tenant_owes__gte', 0)), name='settlement_owed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='settlementdeduction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_deduction_positive'),
        ),
    ]
