# Generated by Django 5.2.17 on 2026-09-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_deposit_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsettlement',
            name='credit_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
