# Generated by Django 5.1.4 on 2026-04-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoicelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSTKRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_ref', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled by User')], db_index=True, default='pending', max_length=15)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_requests', to='payments.invoice')),
            ],
            options={
                'db_table': 'mpesa_stk_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
