# Generated by Django 5.1.4 on 2026-04-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_bank_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankpaymentnotification',
            new_name='bank_paymen_bank_f5165a_idx',
            old_name='bank_notif_bank_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpaymentnotification',
            new_name='bank_paymen_credite_64dcd3_idx',
            old_name='bank_notif_credited_at_idx',
        ),
    ]
