# Generated by Django 5.1.6 on 2026-07-30 12:15

from django.db import migrations, models


def dedupe_invoice_periods(apps, schema_editor):
    """
    Drop money-free duplicate invoices so `invoice_lease_period_unique` can be built.

    WHY: invoices generated before `generate_monthly_invoices` keyed its
    get_or_create on (lease, period_start) duplicated periods that already
    existed under a different invoice_number. A duplicate that carries no money
    is a generator artifact and is safe to remove; one with a payment or a
    non-zero amount_paid is real and is escalated instead of deleted.

    WHY this runs first: MySQL does not roll back DDL. If this step aborts after
    an AddConstraint had already succeeded, the orphaned constraint would block
    every subsequent re-run of this migration.
    """
    Invoice = apps.get_model("payments", "Invoice")

    duplicate_periods = (
        Invoice.objects.values("lease_id", "period_start")
        .annotate(n=models.Count("id"))
        .filter(n__gt=1)
    )

    for group in duplicate_periods:
        rows = list(
            Invoice.objects.filter(
                lease_id=group["lease_id"], period_start=group["period_start"]
            ).order_by("id")
        )
        keeper = max(rows, key=lambda row: (row.amount_paid, -row.id))

        for row in rows:
            if row.pk == keeper.pk:
                continue
            if row.amount_paid or row.payments.exists():
                raise RuntimeError(
                    "Cannot apply invoice_lease_period_unique: lease "
                    f"{group['lease_id']} has multiple invoices for period "
                    f"{group['period_start']} and more than one carries payment "
                    f"data (invoice ids {[r.id for r in rows]}). Merge them by "
                    "hand, then re-run this migration."
                )
            row.delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0006_rename_bank_notif_bank_status_idx_bank_paymen_bank_f5165a_idx_and_more",
        ),
        ("tenants", "0005_alter_maintenancerequest_photo_and_more"),
    ]

    operations = [
        migrations.RunPython(
            dedupe_invoice_periods, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="mpesastkrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled by User"),
                    ("requires_review", "Requires Review"),
                ],
                db_index=True,
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="bankpaymentnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="bank_notification_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_due__gt", 0)),
                name="invoice_amount_due_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__gte", 0)),
                name="invoice_amount_paid_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="invoice_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("lease", "period_start"), name="invoice_lease_period_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="invoice_line_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_reading__isnull", True),
                    ("current_reading__isnull", True),
                    ("current_reading__gte", models.F("previous_reading")),
                    _connector="OR",
                ),
                name="invoice_line_meter_readings_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mpesastkrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="stk_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "confirmed"), _negated=True),
                    ("paid_at__isnull", False),
                    _connector="OR",
                ),
                name="confirmed_payment_has_paid_at",
            ),
        ),
    ]
