# Generated by Django 5.1.6 on 2026-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_alter_mpesastkrequest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankpaymentnotification",
            name="transaction_ref",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="bankpaymentnotification",
            constraint=models.UniqueConstraint(
                fields=("bank", "transaction_ref"),
                name="bank_transaction_reference_unique",
            ),
        ),
    ]
