# Generated by Django 5.2.17 on 2026-08-29 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_invoice_lease_to_tenancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='The user who entered this payment by hand, if anyone did.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
