# Generated by Django 5.2.17 on 2026-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_payment_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='etims_receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number from eTIMS for this rent, if one has been issued.', max_length=50, null=True),
        ),
    ]
