# Generated by Django 5.2.17 on 2026-09-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_etims_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpaymentnotification',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unplaced_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankpaymentnotification',
            name='bank',
            field=models.CharField(choices=[('kcb', 'KCB'), ('equity', 'Equity'), ('mpesa', 'M-Pesa')], db_index=True, max_length=10),
        ),
    ]
