# Generated by Django 5.2.17 on 2026-09-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_bankpaymentnotification_mpesa_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('deposit', 'Deposit applied')], db_index=True, max_length=10),
        ),
    ]
