# Generated by Django 5.2.17 on 2026-09-29 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_method_deposit'),
        ('tenants', '0011_deposit_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carried_parts', to='payments.payment'),
        ),
        migrations.CreateModel(
            name='TenancyCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('deposit', 'Deposit applied')], max_length=10)),
                ('paid_at', models.DateTimeField()),
                ('source_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.payment')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='tenants.tenancy')),
            ],
            options={
                'db_table': 'tenancy_credits',
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_amount_positive'), models.CheckConstraint(condition=models.Q(('remaining__gte', 0), ('remaining__lte', models.F('amount'))), name='credit_remaining_within_amount')],
            },
        ),
    ]
